#!/usr/bin/env sh

GENERAL_DIR=$(pwd)
DIR_NAME=pop
TESTS_DIR=$GENERAL_DIR/$DIR_NAME/tests
PATH_ALLURE=$GENERAL_DIR/allure/bin/allure
PATH_RESULT_ALLURE=$GENERAL_DIR/allure_results/
PATH_TO_POETRY=$GENERAL_DIR/$DIR_NAME

$PATH_TO_POETRY run pytest $TESTS_DIR –alluredir=$PATH_RESULT_ALLURE
sh $PATH_ALLURE serve –port 8080 $PATH_RESULT_ALLURE
